mysql:
  host: 47.100.186.122
  port: 3306
  config: "charset=utf8&parseTime=true&loc=Local"
  db: gvb_db
  user: root
  password: "meixi123"
  logLevel: "dev"
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: "true"
  log_in_console: "true"
system:
  host: 0.0.0.0
  port: 8080
  env: release
upload:
  size: 2
  path: uploads/file
site_info:
  created_at: ""
  bei_an: ""
  title: ""
  qq_image: ""
  version: 6.2.1
  email: ""
  wechat_image: ""
  name: ""
  job: ""
  addr: ""
  slogan: ""
  slogan_en: ""
  web: ""
  bilibili_url: ""
  gitee_url: ""
  github_url: ""
qq:
  app_id: ""
  key: gghj548549jkj784598
  redirect: ""
qi_niu:
  enable: true
  access_key: _s5B-HcWimJDXGL8yBpPguYkhzHQYUyl6yhzXGjE
  secret_key: Bt0g3IaLgpBPQsB84oVuj1lIbTfrmdlHLifG2rJr
  bucket: gotests
  cdn: testgo.club/
  zone: as0
  prefix: "gvb"
  size: 5
email:
  host: smtp.qq.com
  port: 465
  user: 2148583859@qq.com
  password: zhdskujnuanxdiej
  default_from_email: 枫枫知道
  user_ssl: true
  user_tls: false
jwy:
  secret: ""
  expires: 2
  issuer: "test"
redis:
  ip: 47.100.186.122
  port: 6379
  password: "123456"
  pool_size: 100
  